### ISSUE TITLE
Any equivalent to an HStack?

### ISSUE THREAD

**Issue by Mcrich23** [twostraws/Ignite#6]
I am trying to put social links in a footer with the logo and handle aligned horizontally. Ideas?

**Comment by twostraws** [comment]
You should use `Section`, then place your items into there. See here: https://ignitesamples.hackingwithswift.com/grid-examples/

`HStack` is great in SwiftUI, but causes problems on the web because it won't wrap its elements – they always stay in one line, even on (say) on iPhone in portrait orientation.
