### ISSUE TITLE
Run command does not work

### ISSUE THREAD

**Issue by NihalArman** [twostraws/Ignite#61]
Ignite run command gives the following error:
ignite run --preview
❌ This site specifies a custom subfolder, so it can't be previewed locally.

I was able to run my project but suddenly got the above error. After a while it got fixed automatically and then again it returned. There is not much in the project and everything is mostly in the default state

**Comment by twostraws** [comment]
This is likely related to #45 from @gavineadie. Gavin: any ideas?

**Comment by jobearrr** [comment]
I'm also having issues after this change.
I don't quite get why checking for existence of `<link href=\"/css` in `index.html`.
In my case, I created a custom header to add my custom css stylesheet. The css file is in the css subfolder inside Assets.
Observing the generated `index.html`, I see that the link tag does not have a relative but an absolute path, including the domain (I believe it comes from the `url` property for base URL we set on `Site`). So it seems the `run` command will always fail because of the missing link tag with the relative path.

**Comment by gavineadie** [comment]
Sorry for the delay .. just saw these reports.  Checking now ..

**Comment by gavineadie** [comment]
My change #45 is intended to allow the generation of a set of website files that are not at the root of the server.  That is, generating an _Ignite_ site for placement at `https://server.com/mysite` rather than at the default `https://mysite.com` location.  The unexpected consequence of moving the site's root like this is that the `ignite run --preview` will not behave as expected (because `"/"` isn't the site root any more, and `run --preview` relies on that).  Rather than let this behavior confuse and frustrate, I emit the error that @NihalArman received.

A regular _Ignite_ website has a value of `url` in the `struct Site` without any directory name, ie:
```
struct RegularSite: Site {
    var name = "Hello World"
    var url = URL("https://server.com")           // <----
```
and the site's `index.html` file's `<HEAD>` will contain `<link href="/css/bootstrap.min.css"`.

The generation of a non-root set of web files is triggered by, and only by, the value of `url` in the `struct Site` having an appended directory, like `website` below:
```
struct SampleSite: Site {
    var name = "Hello World"
    var url = URL("https://server.com/website")           // <----
```
and now the `index.html` `<HEAD>` contains `<link href="/website/css/bootstrap.min.css" rel="stylesheet">`

An easy, fast way to distinguish a "non-root" usage was to look for a non-root reference to that CSS file and use that as the tigger to emit the error.  I'll be the first to admit this is rather brittle, but it would be worse to not catch it.  Changing Ignite to preview non-root sites is more, and more intrusive, work, than I felt competent to do.

Nearly all my websites are non-root, based in their own directories on the server I use.  Because I can't review them with _Ignite_, I take two approaches:  While building and testing my sites, I do so rooted -- that way `ignite run --preview` works.  When I'm ready to deploy the site, I build it one more time, this time targeting the desired directory, and transfer the files to the server.

In the case of @jobearrr reporting that "created a custom header to add my custom css stylesheet" caused a problem, it would helpful to see the nature of the customization so I can devise a less fragile test (maybe drop an explicit comment into the `<HEAD>` rather than relying on a side-effect).

**Comment by jobearrr** [comment]
@gavineadie Thanks for checking in!
I made a mistake with how I set the base URL for the site.
I had something like 
``` swift
var url = URL("mydomain.com")
```
And the `path` property of `URL("mydomain.com")` will be "mydomain.com".
So that render function
``` swift
public func render(context: PublishingContext) -> String {
    // char[0] of the link 'href' is '/' for an asset; not for a site URL
    let basePath = href.starts(with: "/") ? context.site.url.path : ""
    return "<link href=\"\(basePath)\(href)\" rel=\"\(rel)\">"
}
```
will produce something like `mydomain.com/css/style.css`. 
And `ignite run` will now fail because it cannot find `"<link href=\"/css"` inside `index.html`.

I changed the base URL to contain the HTTP scheme
``` swift
var url = URL("https://mydomain.com")
```

So now the `path` returns the expected value, the `render` function produces a string with `"<link href=\"/css"` and `ignite run` succeeds.
And my case is solved! 😄

**Comment by gavineadie** [comment]
@jobearrr .. I'm glad your problem is resolved.  If _Ignite_ checked that `Site.url.scheme` had a value ("http" or "https") your mistake would have been caught immediately.  Maybe some validation of `Site` properties is needed?

**Comment by jobearrr** [comment]
@gavineadie That sounds like a good idea!

**Comment by twostraws** [comment]
Does this need some further work, or should this issue now be closed?

**Comment by gavineadie** [comment]
I believe it can but closed the OP @NihalArman has not commented on our conversation.

**Comment by NihalArman** [comment]
Hey, sorry for the late response and thanks for the investigation. I think it can be closed as I can't reproduce it anymore

**Comment by mikaelacaron** [comment]
I just created a brand new site, haven't changed anything yet and `ignite run --preview` immediately worked

**Comment by twostraws** [comment]
@mikaelacaron That is certainly the goal 🙂

**Comment by trozware** [comment]
I have further data on this.

I'm deploying a test site using GitHub Pages. In order to make the Bootstrap links work, I have to set the site's `url` to https://trozware.github.io/TrozTest. This gives the preview error "This site specifies a custom subfolder, so it can't be previewed locally.".

If I change the `url` to https://trozware.github.io then the preview works, but the deployed site can't access the Bootstrap files.

**Comment by gavineadie** [comment]
That is the expected behavior @trozware .. The problem arose for someone else (noted in a May 21st entry, and replied to by me a little later) in this issue.  Though you cannot preview the "subfolder" site, it should be correct and movable to the folder where it is intended to be.  My own solution to this inconvenience is to not add the subfolder until I've perfected the site using the preview -- then I add it, build the site one more time, and move it to it's intended location.

**Comment by trozware** [comment]
Thanks @gavineadie that was the solution I came up with too. I just thought this example might help diagnose the issue.
